//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Colors : global::System.Configuration.ApplicationSettingsBase {
        
        private static Colors defaultInstance = ((Colors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Colors())));
        
        public static Colors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beige")]
        public global::System.Drawing.Color DefaultWorkoutControlBackground {
            get {
                return ((global::System.Drawing.Color)(this["DefaultWorkoutControlBackground"]));
            }
            set {
                this["DefaultWorkoutControlBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color ValidPaceColor {
            get {
                return ((global::System.Drawing.Color)(this["ValidPaceColor"]));
            }
            set {
                this["ValidPaceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Salmon")]
        public global::System.Drawing.Color InvalidPaceColor {
            get {
                return ((global::System.Drawing.Color)(this["InvalidPaceColor"]));
            }
            set {
                this["InvalidPaceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlanchedAlmond")]
        public global::System.Drawing.Color ActiveWorkoutControlBackground {
            get {
                return ((global::System.Drawing.Color)(this["ActiveWorkoutControlBackground"]));
            }
            set {
                this["ActiveWorkoutControlBackground"] = value;
            }
        }
    }
}
