//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Misc : global::System.Configuration.ApplicationSettingsBase {
        
        private static Misc defaultInstance = ((Misc)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Misc())));
        
        public static Misc Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int DefaultTrainingPlanLength {
            get {
                return ((int)(this["DefaultTrainingPlanLength"]));
            }
            set {
                this["DefaultTrainingPlanLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("plan")]
        public string LastTrainingPlanName {
            get {
                return ((string)(this["LastTrainingPlanName"]));
            }
            set {
                this["LastTrainingPlanName"] = value;
            }
        }
    }
}
