//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Paces : global::System.Configuration.ApplicationSettingsBase {
        
        private static Paces defaultInstance = ((Paces)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Paces())));
        
        public static Paces Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:15")]
        public global::System.TimeSpan Easy {
            get {
                return ((global::System.TimeSpan)(this["Easy"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan Long {
            get {
                return ((global::System.TimeSpan)(this["Long"]));
            }
            set {
                this["Long"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:55")]
        public global::System.TimeSpan Marathon {
            get {
                return ((global::System.TimeSpan)(this["Marathon"]));
            }
            set {
                this["Marathon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:40")]
        public global::System.TimeSpan Threshold {
            get {
                return ((global::System.TimeSpan)(this["Threshold"]));
            }
            set {
                this["Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:37")]
        public global::System.TimeSpan Halfmarathon {
            get {
                return ((global::System.TimeSpan)(this["Halfmarathon"]));
            }
            set {
                this["Halfmarathon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:30")]
        public global::System.TimeSpan TenK {
            get {
                return ((global::System.TimeSpan)(this["TenK"]));
            }
            set {
                this["TenK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:22")]
        public global::System.TimeSpan FiveK {
            get {
                return ((global::System.TimeSpan)(this["FiveK"]));
            }
            set {
                this["FiveK"] = value;
            }
        }
    }
}
